### ISSUE TITLE
Plunker demo not working

### ISSUE THREAD

**Issue by gabrielemeloncelli** [basvandenberg/ng-select#149]
I reached the link:
https://plnkr.co/edit/JcG8uO9nIfSGMEKdLf0Y?p=preview (from the page https://www.npmjs.com/package/angular2-select)
and it is not working at all.
I fixed the main issue by changing the path to CDN.
In config.js:
...
  packageNames.forEach(function(pkgName) {
    var packageName = pkgName.substring(pkgName.indexOf('/') + 1);
    packages[pkgName] = { main: '/bundles/' + packageName + '.umd.js', defaultExtension: 'js' };
  });

...

See: https://plnkr.co/edit/o6PffQegv4BW6jUju5lA?p=preview

**Comment by basvandenberg** [comment]
Plnkr is fixed.

**Comment by ishandutta2007** [comment]
Still not working or have you not updated readme wit latest link ?
